@echo off
call tools\fileSize.bat RawSize0 "build\page0.bin"
call tools\fileSize.bat PackedSize0 "build\page0.pck"
call tools\fileSize.bat RawSize1 "build\page1.bin"
call tools\fileSize.bat PackedSize1 "build\page1.pck"
call tools\fileSize.bat RawSize2 "build\page2.bin"
call tools\fileSize.bat PackedSize2 "build\page2.pck"
call tools\fileSize.bat RawSize3 "build\page3.bin"
call tools\fileSize.bat PackedSize3 "build\page3.pck"
call tools\fileSize.bat RawSize4 "build\page4.bin"
call tools\fileSize.bat PackedSize4 "build\page4.pck"
call tools\fileSize.bat RawSize5 "build\page5.bin"
call tools\fileSize.bat PackedSize5 "build\page5.pck"
call tools\fileSize.bat RawSize6 "build\page6.bin"
call tools\fileSize.bat PackedSize6 "build\page6.pck"
call tools\fileSize.bat RawSize7 "build\page7.bin"
call tools\fileSize.bat PackedSize7 "build\page7.pck"
